### ISSUE TITLE
เวอร์ชัน macOS แสดงความผิดพลาดเมื่อเลือกบอร์ดเป็น Original Kidbright

### ISSUE THREAD

**Issue by cjaikaeo** [MakerAsia/KBProIDE#3]
เมื่อใช้เวอร์ชันสำหรับ macOS (`KBIDE.Setup.0.3.1.mac.zip`) และเลือกบอร์ด KidBright (Original) ผ่าน Board Manager จะขึ้นความผิดพลาดดังนี้

```
Unhandled Error
Error: Cannot find module 'mkdirp'
    at Object.<anonymous> (/Applications/kbide.app/Contents/boards/kidbright-arduino/compiler.js:2:16)
    at Object.<anonymous> (/Applications/kbide.app/Contents/boards/kidbright-arduino/compiler.js:137:3)
    at Module.fa16 (file:///Applications/kbide.app/Contents/platforms/arduino-esp32/package/arduino-esp32-actionbar/dist/arduino-esp32-actionbar.umd.js:3094:33)
    at __webpack_require__ (file:///Applications/kbide.app/Contents/platforms/arduino-esp32/package/arduino-esp32-actionbar/dist/arduino-esp32-actionbar.umd.js:30:30)
    at file:///Applications/kbide.app/Contents/platforms/arduino-esp32/package/arduino-esp32-actionbar/dist/arduino-esp32-actionbar.umd.js:94:18
    at file:///Applications/kbide.app/Contents/platforms/arduino-esp32/package/arduino-esp32-actionbar/dist/arduino-esp32-actionbar.umd.js:97:10
    at webpackUniversalModuleDefinition (file:///Applications/kbide.app/Contents/platforms/arduino-esp32/package/arduino-esp32-actionbar/dist/arduino-esp32-actionbar.umd.js:9:37)
    at file:///Applications/kbide.app/Contents/platforms/arduino-esp32/package/arduino-esp32-actionbar/dist/arduino-esp32-actionbar.umd.js:10:3
```

**Comment by NAzT** [comment]
fixed in 1.0.0

**Comment by NAzT** [comment]
fixed in 1.0.0
