### ISSUE TITLE
KB-IDE Network error

### ISSUE THREAD

**Issue by bombombombon** [MakerAsia/KBProIDE#48]
พอเปิดขึ้นมาก็ขึ้นแบบนี้ครับ
ก่อนหน้านี้ใช้ได้ปกติ โหลดบอร์ด plugin ได้ปกติครับ
ลบลงใหม่ก็ยังเป็นครับ
(ลงเครื่องอื่นที่ไม่เคยใช้ก็เป็นครับ)
-------------------------------------------------------

When it opens up, it looks like this.
Previously, it can be used normally, the plugin board can be loaded normally.
re-installed, it's still there.

-------------------------------------------------------

Unhandled Promise Rejection
NonError: { code: -1,
  message: 'Network Error',
  error:
   { Error: Network Error
       at e.exports (app://./js/chunk-vendors.096c7f1c.js:168:15184)
       at XMLHttpRequest.h.onerror (app://./js/chunk-vendors.096c7f1c.js:168:14236)
     config:
      { url: 'https://manage.kbide.org//_/items/version',
        method: 'get',
        params: [Object],
        data: '{}',
        headers: [Object],
        baseURL: 'https://manage.kbide.org//_/',
        transformRequest: [Array],
        transformResponse: [Array],
        paramsSerializer: [Function],
        timeout: 600000,
        adapter: [Function],
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus] },
     request: XMLHttpRequest {},
     response: undefined,
     isAxiosError: true,
     toJSON: [Function] } }
    at module.exports.input (C:/Users/COREi3/AppData/Local/Programs/kbide/resources/app.asar/node_modules/ensure-error/index.js:14:10)
    at handleError (C:/Users/COREi3/AppData/Local/Programs/kbide/resources/app.asar/node_modules/electron-unhandled/index.js:21:10)
    at reason (C:/Users/COREi3/AppData/Local/Programs/kbide/resources/app.asar/node_modules/electron-unhandled/index.js:88:4)
    at invokeFunc (C:/Users/COREi3/AppData/Local/Programs/kbide/resources/app.asar/node_modules/lodash.debounce/index.js:160:19)
    at trailingEdge (C:/Users/COREi3/AppData/Local/Programs/kbide/resources/app.asar/node_modules/lodash.debounce/index.js:207:14)
    at timerExpired (C:/Users/COREi3/AppData/Local/Programs/kbide/resources/app.asar/node_modules/lodash.debounce/index.js:195:14)
![1685432631710](https://github.com/MakerAsia/KBProIDE/assets/135005660/c7892cd5-7584-4953-86be-dc503e0fceb1)

**Comment by semaspu** [comment]
Please

**Comment by ChamnanR** [comment]
Please

**Comment by UdomSladtookha** [comment]
ลงบน Macbook Pro m2 เจอแบบนี้ทั้งฝั่ง mac และ VM win11
