### ISSUE TITLE
บน macOS เปิดโปรแกรมแล้วขึ้น error 

### ISSUE THREAD

**Issue by anoochit** [MakerAsia/KBProIDE#5]
บน macOS เปิดโปรแกรมแล้วขึ้น error 

TypeError: Cannot read property 'platform' of undefined
    at g (app://./js/app.242cbfcb.js:1:157919)
    at Object.T [as packages] (app://./js/app.242cbfcb.js:1:161348)
    at Module.56d7 (app://./js/app.242cbfcb.js:1:87204)
    at l (app://./js/app.242cbfcb.js:1:2324)
    at Object.0 (app://./js/app.242cbfcb.js:1:7702)
    at l (app://./js/app.242cbfcb.js:1:2324)
    at a (app://./js/app.242cbfcb.js:1:388)
    at 0 (app://./js/app.242cbfcb.js:1:7667)
    at app://./js/app.242cbfcb.js:1:7672

![Imgur](https://i.imgur.com/ApoQwDMl.png)

**Comment by comdet** [comment]
เปิด View->Toggle Developer Tools แล้วใช้คำสั่ง localStorage.clear(); ตรง console สามารถแก้ไขได้ไหมครับ

**Comment by anoochit** [comment]
เดี๋ยวลองดูครับ

อนุชิต
